### ISSUE TITLE
Reproducing paper results

### ISSUE THREAD

**Issue by gcunhase** [kumar-shridhar/Know-Your-Intent#3]
Hello, 

I'm trying to reproduce your paper results. Should I run `updated_semhash_pipeline.ipynb` or `comprehensive_semhash_test.ipynb`? What's the difference between the two scripts?

Thanks in advance

**Comment by kumar-shridhar** [comment]
Hello @gcunhase.

Either one will lead to the same results. Updated ```updated_semhash_pipeline``` is a Jupyter notebook file with some visualization. 
```comprehensive_semhash_test.ipynb``` is a python file which we used to run multiple times to average the results mentioned in the paper. So if you want to run it multiple times, go for ```comprehensive_semhash_test.ipynb```.  

The paper has been accepted for the Oral presentation at IJCNN 19 and after the event in July, the ArXiv version will be updated.
