### ISSUE TITLE
Minimal example

### ISSUE THREAD

**Issue by elyase** [kumar-shridhar/Know-Your-Intent#4]
Hi guys, I would like to try your method but it is not clear to me where to start. Lets say I have:

```
sentences = ['Hi', 'mood morning', 'bye', 'good bye']
intents = ['greet', 'greet', 'bye', 'bye']
```

What are the steps, functions (from which notebooks) I have to follow to in order to train / test the model?

**Comment by kumar-shridhar** [comment]
Hi,
For this please create the file with sentences and their respective intents and change the reading file method. That's all needs to be done for a different data format. 
For the task, the following data format in JSON has been used: [link](https://github.com/sebischair/NLU-Evaluation-Corpora/blob/master/AskUbuntuCorpus.json)

**Comment by elyase** [comment]
Thanks for your reply. What reading file method should I change and what are the next steps after changing that? There are many files scripts in the repo and it is not clear where to start.

**Comment by kumar-shridhar** [comment]
Run the semhash pipeline jupyter notebook and change the first few cells with the correct data file path and type. Rest all scripts should work fine.

**Comment by elyase** [comment]
thanks for specifying the file that should be run. After I run the whole notebook: how do I get the predicted labels for my sentences? Also do I need to run the whole notebook if I only want to train/get predictions on my in memory data?

**Comment by kumar-shridhar** [comment]
For inference, you need to save the checkpoint and call the `.predict` function of the classifier used.
